### PR TITLE
Fixed issue #2

### PR DESCRIPTION
**Pull request by TDFKAOlli**
Fixed issue #2 by providing patch for knockd uninitialized vars for tcpflags

### CODE REVIEW

**Comment by milaq** [comment]
thanks for your efforts.
i am currently on a tight work schedule abroad; i will get to this when i am back asap.

cheers

**Comment by TDFKAOlli** [comment]
Sure, no hurry. :-) I have it working now for a few days and it looks fine, but leaves more time for testing it. ;-)

**Comment by milaq** [comment]
I have integrated your tcpflags patch for now.
Thanks for that again.

I'll have a look at the latest upstream tree to see what else can eventually be merged.

**Comment by TDFKAOlli** [comment]
O.k. Thanks!

I also tried to build the latest commits from the knock project, changing the Makefile to fetch git master from the knock github project. But I couldn't get it compiled as it failed to configure correctly. I don't have enough understanding of the OpenWRT/LEDE build process and makefile syntax to find out what is going wrong.
In general there are several patches incorporated compared to the 0.7 and also several pull request with useful features. If you find time to check how to get github master compile that would be great.

**Comment by TDFKAOlli** [comment]
This pull request isn't anymore needed, when pull request #5 is accepted. The fixes proposed here are nearly all already included in the github version of knock. Only the access to "attempt->srchost" before the check for "attempt" to be non-null is not included yet.

**Pull request closed without merging**
